CREATE TABLE `mapeamento` ( 
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`tipo` VARCHAR(255) INT(11) FLOAT NULL DEFAULT NULL,
	`latitude` VARCHAR(255) INT(11) FLOAT NULL DEFAULT NULL,
	`longitude` VARCHAR(255) INT(11) FLOAT NULL DEFAULT NULL,
	`color` VARCHAR(255) INT(11) FLOAT NULL DEFAULT NULL,
	`link` VARCHAR(255) INT(11) FLOAT NULL DEFAULT NULL,
	`observacoes` TEXT NULL,
	`last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1;
